vim.keymap.set("n", "<C-L>", function()
  vim.fn.execute(":w")
  local filename = vim.fn.expand("%")
  filename = filename:gsub("%[", "\\[")
  filename = filename:gsub("%]", "\\]")
  filename = filename:gsub("%(", "\\(")
  filename = filename:gsub("%)", "\\)")
  vim.fn.execute("!npx prettier --stdin-filepath --write " .. filename)
end)
